'use client';

import { useState, useRef, useEffect } from 'react';
import { Send, GitBranch, Settings, DollarSign, Loader2, Check, X, GitPullRequest, Trash2, GitMerge } from 'lucide-react';
import { Message, Session, Settings as SettingsType, CostTracker } from '@/types';

export default function Home() {
  // State
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [session, setSession] = useState<Session>({});
  const [showSettings, setShowSettings] = useState(false);
  const [showSetup, setShowSetup] = useState(true);
  const [costTracker, setCostTracker] = useState<CostTracker>({
    sessionCost: 0,
    dailyCost: 0,
    monthlyCost: 0,
    tokensUsed: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
  });
  const [settings, setSettings] = useState<SettingsType>({
    deployMode: 'safe',
    model: 'sonnet',
    enableMultiModelRouting: false,
    enableConversationCompression: false,
    tokenBudget: { enabled: false, perSession: 5, perDay: 20 },
    preBuiltCommands: false,
  });
  const [currentBranch, setCurrentBranch] = useState<string>('');
  const [prUrl, setPrUrl] = useState<string>('');

  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Handle setup form
  const handleSetup = (e: React.FormEvent) => {
    e.preventDefault();
    if (session.anthropicKey && session.githubToken && session.repo) {
      setShowSetup(false);
    }
  };

  // Generate branch name from task
  const generateBranchName = (task: string): string => {
    const words = task.toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .slice(0, 4)
      .join('-');
    return `feature/${words}-${Date.now().toString(36).slice(-4)}`;
  };

  // Create a new branch
  const createBranch = async (branchName: string) => {
    const response = await fetch('/api/github', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'create',
        token: session.githubToken,
        owner: session.repo?.owner,
        repo: session.repo?.name,
        branchName,
        fromBranch: session.repo?.defaultBranch || 'main',
      }),
    });
    const data = await response.json();
    if (data.error) throw new Error(data.error);
    return data.branch;
  };

  // Create PR
  const createPR = async (title: string, branchName: string) => {
    const response = await fetch('/api/github', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'createPR',
        token: session.githubToken,
        owner: session.repo?.owner,
        repo: session.repo?.name,
        title,
        body: `Created by Claude Coder\n\nChanges made in this PR were generated by AI.`,
        head: branchName,
        base: session.repo?.defaultBranch || 'main',
      }),
    });
    const data = await response.json();
    if (data.error) throw new Error(data.error);
    return data.pr;
  };

  // Send message
  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
      // In safe mode, create a branch first if not already on one
      let workingBranch = currentBranch;
      if (settings.deployMode === 'safe' && !currentBranch) {
        const branchName = generateBranchName(input);
        await createBranch(branchName);
        workingBranch = branchName;
        setCurrentBranch(branchName);
        
        // Add system message about branch
        setMessages(prev => [...prev, {
          id: `branch-${Date.now()}`,
          role: 'assistant',
          content: `📦 Created branch \`${branchName}\` for safe editing. Your main branch is protected.`,
          timestamp: new Date(),
        }]);
      }

      // Send to API
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: input,
          conversationHistory: messages.map(m => ({
            role: m.role,
            content: m.content,
          })),
          settings,
          session: {
            ...session,
            currentBranch: workingBranch || session.repo?.defaultBranch,
          },
        }),
      });

      const data = await response.json();

      if (data.error) {
        throw new Error(data.error);
      }

      const assistantMessage: Message = {
        id: Date.now().toString(),
        role: 'assistant',
        content: data.content,
        timestamp: new Date(),
        cost: data.cost,
        tokensUsed: data.tokensUsed,
        filesChanged: data.filesChanged,
      };

      setMessages(prev => [...prev, assistantMessage]);
      
      if (data.costTracker) {
        setCostTracker(data.costTracker);
      }

    } catch (error: any) {
      setMessages(prev => [...prev, {
        id: Date.now().toString(),
        role: 'assistant',
        content: `❌ Error: ${error.message}`,
        timestamp: new Date(),
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  // Merge to main
  const handleMerge = async () => {
    if (!currentBranch) return;
    
    try {
      setIsLoading(true);
      
      // Create PR first
      const pr = await createPR(`Changes from Claude Coder`, currentBranch);
      setPrUrl(pr.url);

      // Merge it
      await fetch('/api/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'merge',
          token: session.githubToken,
          owner: session.repo?.owner,
          repo: session.repo?.name,
          prNumber: pr.number,
        }),
      });

      // Delete branch
      await fetch('/api/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'delete',
          token: session.githubToken,
          owner: session.repo?.owner,
          repo: session.repo?.name,
          branchName: currentBranch,
        }),
      });

      setMessages(prev => [...prev, {
        id: `merge-${Date.now()}`,
        role: 'assistant',
        content: `✅ Merged to main and cleaned up branch. Your changes are now live!`,
        timestamp: new Date(),
      }]);

      setCurrentBranch('');
      setPrUrl('');

    } catch (error: any) {
      setMessages(prev => [...prev, {
        id: `error-${Date.now()}`,
        role: 'assistant',
        content: `❌ Merge failed: ${error.message}`,
        timestamp: new Date(),
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  // Discard branch
  const handleDiscard = async () => {
    if (!currentBranch) return;
    
    try {
      setIsLoading(true);
      
      await fetch('/api/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'delete',
          token: session.githubToken,
          owner: session.repo?.owner,
          repo: session.repo?.name,
          branchName: currentBranch,
        }),
      });

      setMessages(prev => [...prev, {
        id: `discard-${Date.now()}`,
        role: 'assistant',
        content: `🗑️ Discarded branch \`${currentBranch}\`. Main branch unchanged.`,
        timestamp: new Date(),
      }]);

      setCurrentBranch('');

    } catch (error: any) {
      setMessages(prev => [...prev, {
        id: `error-${Date.now()}`,
        role: 'assistant',
        content: `❌ Failed to discard: ${error.message}`,
        timestamp: new Date(),
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  // Setup screen
  if (showSetup) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <div className="w-full max-w-md bg-dark-800 rounded-xl border border-dark-600 p-8">
          <h1 className="text-2xl font-bold mb-2 text-center">🚀 Claude Coder</h1>
          <p className="text-gray-400 text-center mb-8">Connect your API keys to get started</p>
          
          <form onSubmit={handleSetup} className="space-y-6">
            <div>
              <label className="block text-sm text-gray-400 mb-2">Anthropic API Key</label>
              <input
                type="password"
                value={session.anthropicKey || ''}
                onChange={e => setSession(s => ({ ...s, anthropicKey: e.target.value }))}
                placeholder="sk-ant-..."
                className="w-full bg-dark-700 border border-dark-500 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-claude-orange"
                required
              />
              <p className="text-xs text-gray-500 mt-1">
                Get from <a href="https://console.anthropic.com" target="_blank" className="text-claude-orange hover:underline">console.anthropic.com</a>
              </p>
            </div>

            <div>
              <label className="block text-sm text-gray-400 mb-2">GitHub Personal Access Token</label>
              <input
                type="password"
                value={session.githubToken || ''}
                onChange={e => setSession(s => ({ ...s, githubToken: e.target.value }))}
                placeholder="ghp_..."
                className="w-full bg-dark-700 border border-dark-500 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-claude-orange"
                required
              />
              <p className="text-xs text-gray-500 mt-1">
                Needs repo scope. <a href="https://github.com/settings/tokens/new?scopes=repo" target="_blank" className="text-claude-orange hover:underline">Create token</a>
              </p>
            </div>

            <div>
              <label className="block text-sm text-gray-400 mb-2">Repository</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={session.repo?.owner || ''}
                  onChange={e => setSession(s => ({ 
                    ...s, 
                    repo: { ...s.repo, owner: e.target.value, name: s.repo?.name || '', defaultBranch: 'main' }
                  }))}
                  placeholder="owner"
                  className="w-1/3 bg-dark-700 border border-dark-500 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-claude-orange"
                  required
                />
                <span className="text-gray-500 self-center">/</span>
                <input
                  type="text"
                  value={session.repo?.name || ''}
                  onChange={e => setSession(s => ({ 
                    ...s, 
                    repo: { ...s.repo, owner: s.repo?.owner || '', name: e.target.value, defaultBranch: 'main' }
                  }))}
                  placeholder="repo"
                  className="flex-1 bg-dark-700 border border-dark-500 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-claude-orange"
                  required
                />
              </div>
            </div>

            <button
              type="submit"
              className="w-full bg-claude-orange hover:bg-opacity-90 text-white font-medium py-3 rounded-lg transition-all"
            >
              Connect & Start
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-dark-600 px-4 py-3 flex items-center justify-between bg-dark-800">
        <div className="flex items-center gap-4">
          <h1 className="text-lg font-semibold">Claude Coder</h1>
          <span className="text-sm text-gray-400">
            {session.repo?.owner}/{session.repo?.name}
          </span>
        </div>
        
        <div className="flex items-center gap-4">
          {/* Branch indicator */}
          {currentBranch && (
            <div className="flex items-center gap-2 bg-dark-700 px-3 py-1.5 rounded-lg">
              <GitBranch className="w-4 h-4 text-green-400" />
              <span className="text-sm">{currentBranch}</span>
            </div>
          )}
          
          {/* Cost display */}
          <div className="flex items-center gap-2 text-sm text-gray-400">
            <DollarSign className="w-4 h-4" />
            <span>${costTracker.sessionCost.toFixed(4)}</span>
          </div>
          
          {/* Settings */}
          <button
            onClick={() => setShowSettings(!showSettings)}
            className="p-2 hover:bg-dark-700 rounded-lg transition-colors"
          >
            <Settings className="w-5 h-5" />
          </button>
        </div>
      </header>

      {/* Settings Panel */}
      {showSettings && (
        <div className="border-b border-dark-600 px-4 py-4 bg-dark-800 slide-up">
          <div className="max-w-3xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-xs text-gray-400 mb-1">Deploy Mode</label>
              <select
                value={settings.deployMode}
                onChange={e => setSettings(s => ({ ...s, deployMode: e.target.value as 'safe' | 'direct' }))}
                className="w-full bg-dark-700 border border-dark-500 rounded px-2 py-1.5 text-sm"
              >
                <option value="safe">Safe (branch + PR)</option>
                <option value="direct">Direct (push to main)</option>
              </select>
            </div>
            
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={settings.enableMultiModelRouting}
                onChange={e => setSettings(s => ({ ...s, enableMultiModelRouting: e.target.checked }))}
                className="rounded"
              />
              <span className="text-sm">Multi-model routing</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={settings.preBuiltCommands}
                onChange={e => setSettings(s => ({ ...s, preBuiltCommands: e.target.checked }))}
                className="rounded"
              />
              <span className="text-sm">Pre-built commands</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={settings.tokenBudget.enabled}
                onChange={e => setSettings(s => ({ 
                  ...s, 
                  tokenBudget: { ...s.tokenBudget, enabled: e.target.checked }
                }))}
                className="rounded"
              />
              <span className="text-sm">Token budget</span>
            </label>
          </div>
        </div>
      )}

      {/* Chat Messages */}
      <main className="flex-1 overflow-y-auto p-4">
        <div className="max-w-3xl mx-auto space-y-4">
          {messages.length === 0 && (
            <div className="text-center py-12 text-gray-500">
              <p className="text-lg mb-2">👋 Ready to code!</p>
              <p className="text-sm">Describe what you want to build or fix.</p>
            </div>
          )}
          
          {messages.map(message => (
            <div
              key={message.id}
              className={`slide-up ${
                message.role === 'user' ? 'flex justify-end' : ''
              }`}
            >
              <div
                className={`max-w-[85%] rounded-xl px-4 py-3 ${
                  message.role === 'user'
                    ? 'bg-claude-orange text-white'
                    : 'bg-dark-700 border border-dark-600'
                }`}
              >
                <div className="whitespace-pre-wrap">{message.content}</div>
                
                {/* File changes indicator */}
                {message.filesChanged && message.filesChanged.length > 0 && (
                  <div className="mt-3 pt-3 border-t border-dark-500">
                    <p className="text-xs text-gray-400 mb-2">Files changed:</p>
                    {message.filesChanged.map((f, i) => (
                      <div key={i} className="text-xs font-mono text-gray-300">
                        {f.action === 'create' ? '+ ' : '~ '}{f.path}
                      </div>
                    ))}
                  </div>
                )}
                
                {/* Cost indicator */}
                {message.cost !== undefined && (
                  <div className="mt-2 text-xs text-gray-400">
                    ${message.cost.toFixed(4)} • {message.tokensUsed?.input || 0} in / {message.tokensUsed?.output || 0} out
                    {message.tokensUsed?.cacheRead ? ` (${message.tokensUsed.cacheRead} cached)` : ''}
                  </div>
                )}
              </div>
            </div>
          ))}
          
          {isLoading && (
            <div className="flex gap-2 items-center text-gray-400 slide-up">
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>Claude is thinking...</span>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>
      </main>

      {/* Branch Actions */}
      {currentBranch && !isLoading && (
        <div className="border-t border-dark-600 px-4 py-3 bg-dark-800">
          <div className="max-w-3xl mx-auto flex items-center justify-between">
            <div className="text-sm text-gray-400">
              Changes are on <span className="text-white font-mono">{currentBranch}</span>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDiscard}
                className="flex items-center gap-2 px-4 py-2 bg-dark-700 hover:bg-dark-600 rounded-lg transition-colors text-red-400"
              >
                <Trash2 className="w-4 h-4" />
                Discard
              </button>
              <button
                onClick={handleMerge}
                className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-500 rounded-lg transition-colors text-white"
              >
                <GitMerge className="w-4 h-4" />
                Merge to Main
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Input */}
      <div className="border-t border-dark-600 p-4 bg-dark-800">
        <div className="max-w-3xl mx-auto flex gap-3">
          <input
            type="text"
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && !e.shiftKey && handleSend()}
            placeholder="Describe what you want to build or fix..."
            className="flex-1 bg-dark-700 border border-dark-500 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-claude-orange"
            disabled={isLoading}
          />
          <button
            onClick={handleSend}
            disabled={isLoading || !input.trim()}
            className="bg-claude-orange hover:bg-opacity-90 disabled:opacity-50 disabled:cursor-not-allowed px-5 py-3 rounded-xl transition-all"
          >
            <Send className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
}
